version: '3.8'

services:
  web:
    build:
      context: ./hotel
      dockerfile: Dockerfile
    image: hotel-api:latest
    container_name: hotel_api
    restart: unless-stopped
    env_file: .env
    volumes:
       - ./hotel:/app
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: hotel_pgdb
    restart: unless-stopped
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
    volumes:
      - hotel-pgdb-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  hotel-pgdb-volume:
    driver: local
